#!/bin/bash
set -euo pipefail
mkdir -p logs
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0000.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0001.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0002.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0003.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0004.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0005.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0006.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0007.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0008.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0009.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0010.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0011.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0012.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0013.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0014.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0015.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0016.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0017.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0018.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0019.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0020.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0021.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0022.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0023.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0024.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0025.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0026.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0027.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0028.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0029.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0030.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0031.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0032.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0033.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0034.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0035.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0036.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0037.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0038.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0039.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0040.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0041.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0042.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0043.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0044.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0045.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0046.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0047.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0048.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0049.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0050.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0051.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0052.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0053.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0054.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0055.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0056.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0057.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0058.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0059.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0060.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0061.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0062.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0063.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0064.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0065.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0066.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0067.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0068.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0069.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0070.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0071.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0072.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0073.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0074.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0075.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0076.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0077.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0078.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0079.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0080.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0081.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0082.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0083.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0084.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0085.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0086.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0087.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0088.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0089.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0090.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0091.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0092.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0093.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0094.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0095.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0096.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0097.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0098.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0099.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0100.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0101.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0102.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0103.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0104.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0105.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0106.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0107.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0108.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0109.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0110.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0111.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0112.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0113.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0114.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0115.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0116.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0117.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0118.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0119.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0120.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0121.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0122.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0123.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0124.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0125.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0126.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0127.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0128.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0129.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0130.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0131.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0132.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0133.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0134.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0135.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0136.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0137.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0138.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0139.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0140.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0141.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0142.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0143.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0144.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0145.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0146.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0147.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0148.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0149.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0150.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0151.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0152.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0153.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0154.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0155.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0156.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0157.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0158.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0159.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0160.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0161.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0162.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0163.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0164.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0165.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0166.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0167.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0168.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0169.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0170.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0171.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0172.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0173.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0174.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0175.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0176.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0177.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0178.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0179.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0180.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0181.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0182.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0183.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0184.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0185.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0186.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0187.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0188.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0189.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0190.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0191.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0192.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0193.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0194.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0195.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0196.sh
sbatch /gpfs/projects/bsc88/speech/mm_s2st/repos/paraling_speech/src/speechLLM/batches/batch_0197.sh
